### ISSUE TITLE
[BUG] Problem permission tradeshop.edit (tested on localhost)

### ISSUE THREAD

**Issue by kyrtion** [SparklingComet/TradeShop#108]
### Expected behavior

Problem permission tradeshop.edit, if not grated perms.
For example, set default:
tradeshop.create
tradeshop.info
Next up, check my account, not grated OP, Staff, Admin, etc. like be player, not grated perms 100%.

### Observed/Actual behavior

--- ---

### Steps/models to reproduce

HAVE PERMISSION: .CREATE or MANAGER 
1. Set trade
2. /ts edit
3. GUI Opened

### Plugin list

[00:25:18 INFO]: Plugins (7): AuthMe, Essentials, LuckPerms, PlaceholderAPI, ProtocolLib, TradeShop, Vault
(all green)

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

[00:29:49] [Server thread/INFO]: This server is running Paper version git-Paper-304 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 90f717f)
You are running the latest version
[00:29:51] [Server thread/INFO]: 
TradeShop 2.3.1-STABLE by Lori00 & KillerOfPie

/tradeshop   Display help message
/ts help   Display help message
/ts setup   Display shop setup tutorial
/ts bugs   Report bugs to the developers
/ts playerlevel   If Internal Permissions is enable this allows the getting and setting of player permission levels.
/ts reload   Reload configuration files

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

**Comment by SparklingComet** [comment]
I'm not sure I understand the issue, can you be a bit more exhaustive when filling out Expected and Observed behaviour.

**Comment by kyrtion** [comment]
> I'm not sure I understand the issue, can you be a bit more exhaustive when filling out Expected and Observed behaviour.

i dont know how to do. i am russian

**Comment by SparklingComet** [comment]
Expected behaviour means what should happen

Observed behaviour means what you see

Please fill those out.

**Comment by kyrtion** [comment]
Okay, will duplicate.
1. Set group DEFAULT perms: tradeshop.create, tradeshop.info and tradeshop.who.
2. Create chest random trade for test.
3. Send command /td edit.
4. And give player shop MANAGER for edit trade (NO GUI).
5. Player need send command /td edit.

Expected behavior: Chat: Are you(IM/PLAYER) not have permission tradeshop.edit.
Actual behavior: IM/PLAYER opened GUI for edit shop(head, world and etc), 5-7 index for example.

**Comment by SparklingComet** [comment]
So you have a shop manager without TS edit perms but the TS edit command works?

**Comment by kyrtion** [comment]
> So you have a shop manager without TS edit perms but the TS edit command works?

Yeah

**Comment by KillerOfPie** [comment]
Did not test this but it should be fixed in #111

**Comment by kyrtion** [comment]
If realesed or dev version, will tested

**Comment by SparklingComet** [comment]
It was released as a dev version.

**Comment by kyrtion** [comment]
Fixed, thank you a lot
