### ISSUE TITLE
Avoid `/ts what` and `various` when single type of item

### ISSUE THREAD

**Issue by Svish** [SparklingComet/TradeShop#112]
### Is your feature request related to a problem?

Wanted to make a server farm for earning diamonds by selling carrots and potatoes. I set the price to 128 Carrots for 1 Diamond.

This results in the sign showing `1 DIAMOND > Use '/ts what'`, and right-clicking the sign (without enough carrots)  gives the text `You do not have 128 various!`, which is a bit confusing when it's just one kind of item for trade.

### Describe the solution you'd like.

Would be great if the sign and the message would try to avoid using `various` and `Use '/ts what'` when there's only a single kind of item. Could also take the amount into account, maybe could be configurable, with a default of for example up to 3 digits.

This way, you could have trades for multiple stacks of the same item, while still having easy to read signs and messages in chat. 👍

### Describe alternatives you've considered.

One can add another sign next to the shop-sign and type it out manually, or use an item frame with the item, or something like that, but would be so much easier and less fiddly if the plugin would show it directly instead.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported TradeShop build.
- [ ] I have asked the Developers and they have confirmed that it is not already in development.

### Other

![image](https://user-images.githubusercontent.com/142162/140632561-ecde9fe2-bd72-41c2-9f1d-4d4333f5504e.png)

**Comment by KillerOfPie** [comment]
This has already been changed in #111 and should be out in the next couple days.
