### ISSUE TITLE
[Suggestion] Complete freedom with admin mode

### ISSUE THREAD

**Issue by Teslicek** [SparklingComet/TradeShop#114]
### Is your feature request related to a problem?

Yes it is. I want to be able to edit other's chestshops using commands and not the gui, which is really confusing and hard to use (for someone as stupid as me). I want to be able to edit all the properties of the chestshop without limitations.

![image](https://user-images.githubusercontent.com/87967222/141999211-ec46c8b0-5302-4205-bc1f-1873a1df0a4c.png)

### Describe the solution you'd like.

That's why I suggest that with admin mode turned on, you can edit other's chest shops as if they were yours and you can edit any user (owners, managers, members), use any command without getting the error message that you do not have the permissions to edit the shop...

### Describe alternatives you've considered.

I tried using /ts setcost, /ts setproduct, /ts addmanager, /ts addmember on shops that are not mine to edit them, or to help players, but I couldnt really do that, which was really a pain.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported TradeShop build.
- [X] I have asked the Developers and they have confirmed that it is not already in development.

**Comment by KillerOfPie** [comment]
@Teslicek Try out the newest dev release and let me know if it functions the way you need it to
