### ISSUE TITLE
Permission to USE TradeShop

### ISSUE THREAD

**Issue by LKits** [SparklingComet/TradeShop#117]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Please add a permission to USE TradeShop.
So I can give permission to specific group that can use TradeShop.

For example:
tradeshop.use

### Describe alternatives you've considered.

At the moment aren't any.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported TradeShop build.
- [X] I have asked the Developers and they have confirmed that it is not already in development.

**Comment by SparklingComet** [comment]
Hi there, thanks for the suggestion.
As a counter-suggestion, how about adding a permission (such as `tradeshop.noTrade`) to _stop users from buying_ from shops instead?
I believe this would also be a solution to the situation you pointed out on Discord.

**Comment by LKits** [comment]
tradeshop.noTrade doesn't seem to be doing anything.
Permission group that I added "tradeshop.noTrade allow" to can still buy from the shop.

**Comment by SparklingComet** [comment]
There seems to be a misunderstanding. That permission does not yet exist, we're suggesting to add it.

**Comment by LKits** [comment]
That would certainly solve my situation. And I understand why you don't want to add "whitelist" permission, then your plugin wouldn't work "out-of-box".
"Blacklist" permission would work great!

**Comment by SparklingComet** [comment]
> That would certainly solve my situation. And I understand why you don't want to add "whitelist" permission, then your plugin wouldn't work "out-of-box".

Yes that is part of the rationale. Alright then, we'll add this to the todo list for the next release.

**Comment by KillerOfPie** [comment]
@LKits Try out the newest dev release and let me know if it functions the way you need it to

The permission is `tradeshop.prevent-trade`

**Comment by LKits** [comment]
Works perfectly, thank you very much!
