### ISSUE TITLE
How to add another language ?

### ISSUE THREAD

**Issue by tstoco** [SparklingComet/TradeShop#122]
### Is your feature request related to a problem?

I am planning to translate the plugin to Brazilian Portuguese. However, I am not sure how to add it.

Could you explain, please?

### Describe the solution you'd like.

N/A

### Describe alternatives you've considered.

N/A

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported TradeShop build.
- [X] I have asked the Developers and they have confirmed that it is not already in development.

**Comment by KillerOfPie** [comment]
I will be adding a wiki page for this in the next week or 2 with more detail. See below for now though.





Then new Lang file is at the link below. This file allows you to not only change the default values but also the formatting of both Settings and Messages. File names should be based on the language codes found here: https://www.andiamo.co.uk/resources/iso-language-codes/

If you want to test, you can change the `language` value to the name of the new file in Message once it has been created. You should be able to add your language file to the jar using any archive manager, then just add the file to the `Lang` folder.

I think there are plenty of examples for everything that can be used in the file(will add all info to the wiki when I make it). The file is formatted and read as Json so spaces are important, if you are having problems you can use online json parsers to check if the file is valid. 

You can create a pull request to add your file to the code once it is ready and we will review it(as much as we can without being able to read it) 

If you have any questions reply here or @ me on discord. 

https://github.com/Tradeshop/TradeShop/tree/master/src/main/resources/Lang

**Comment by SparklingComet** [comment]
> https://github.com/Tradeshop/TradeShop/tree/2.5.0/src/main/resources/Lang
For posterity:
https://github.com/Tradeshop/TradeShop/tree/master/src/main/resources/Lang

**Comment by SparklingComet** [comment]
TS has had full custom language support for a while, closing.
