### ISSUE TITLE
Trade signs with multiple costs down work

### ISSUE THREAD

**Issue by Ryne9732** [SparklingComet/TradeShop#126]
### Expected behavior

Players should be allowed to trade with a sign with multiple costs as a sudo "crafting" system.
I am using special custom items through naming, lore, and enchants, but I also tried with very vanilla items and the same problem arose.

### Observed/Actual behavior

It disregards all items and just says "You do not have (number of items) Various!"

### Steps/models to reproduce

Make a sign with multiple costs and right click it to buy.

### Plugin list

Citizens, DamageIndicator, Dungeons, Eco, EcoEnchants, Essentials, EssentialsChat, floodgate, Geyser-Spigot, HealthBar, Ilira (Custom one made by a friend to kill entities when they get to close), ItemEdit, KeepChunks, LibsDisguises, LPC, Luckperms, LuckPermsGUI. Minepacks, MyPet, Nicknames, OpenInv, ToolandFoodFX, TradeShop, WorldEdit, WorldGuard.

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

TradeShop 2.5.0 STABLE
1.18.2 Paper

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

**Comment by KillerOfPie** [comment]
This is already fixed in the [dev version](https://github.com/Tradeshop/TradeShop/releases/tag/tradeshop-2.5.1-DEV-2022-04-10T20.47.29) which should be releasing as v2.5.1 soon(#124)
