### ISSUE TITLE
Configurable Default Text Colour on Signs

### ISSUE THREAD

**Issue by KillerOfPie** [SparklingComet/TradeShop#135]
Add config settings for each sign type that allows the default colour of the signs text to be changed

This color will generally only affect the middle rows of the signs as the top and bottom have their own colours that are configurable.

Dark_Oak signs should default to white
All others should be black

**Comment by SparklingComet** [comment]
> Add config settings for each sign type that allows the **user** to configure the default colour of the signs text.

Wdym "user"? You mean admin, right? As in it is set in the config, not individually by players for their own shop

**Comment by KillerOfPie** [comment]
> > Add config settings for each sign type that allows the **user** to configure the default colour of the signs text.
> 
> Wdym "user"? You mean admin, right? As in it is set in the config, not individually by players for their own shop

My bad, yes. fixed it above

**Comment by KillerOfPie** [comment]
Fixed in #127
