### ISSUE TITLE
Hopper Improvements

### ISSUE THREAD

**Issue by KillerOfPie** [SparklingComet/TradeShop#136]
- Block placement of hoppers below a shop if the placer does not have Owner(possibly Manager+) permissions
- Add per shop settings for import/export if the server has them enabled
- Add limiter settings to allow/block product, cost, and/or other items from hopper import/export
- Add player settings to be able to set default for placed shops settings(import/export)

**Comment by DaddyRobLIVE** [comment]
+1 please implement this so we don't need need to use other chest protection plugins and it would be easier for us to restock our shops.

**Comment by KillerOfPie** [comment]
![Screenshot_20220819-222016_Chrome](https://user-images.githubusercontent.com/7243280/185730268-a6412185-0ab8-4842-852b-db0c0636b644.jpg)
Already implemented in the dev version

> +1 please implement this so we don't need need to use other chest protection plugins and it would be easier for us to restock our shops.

**Comment by DaddyRobLIVE** [comment]
Ohhh thanks for quoting it.

**Comment by KillerOfPie** [comment]
Fixed in #127
