### ISSUE TITLE
Permission improvements

### ISSUE THREAD

**Issue by KillerOfPie** [SparklingComet/TradeShop#138]
- Register all permissions using getPluginManager#addPermission
- Add default state and description to all permissions in the enum
- If Permissions properly work without a permissions plugin and with internal-permissions disabled then remove internal permissions.

Test Points:
- Permissions should now show up in Luckperms auto-fill
- Permissions may work without a permissions plugin and with internal-permissions disabled

**Comment by SparklingComet** [comment]
|Name|Enabled by default?|
|------|------|
|Help | :heavy_check_mark:|
| Create | :heavy_check_mark: |
| Create Infinite | :x: |
| Create Bi | :heavy_check_mark: |
| Admin | :x: |
| Edit | :heavy_check_mark: |
| Info | :heavy_check_mark: |
| Manage Plugin | :x: |
| Prevent Trade -> Trade | :heavy_check_mark:|

**Comment by SparklingComet** [comment]
we might not need the "internal level" anymore

**Comment by SparklingComet** [comment]
Also, I think the default status should **not** be made configurable

**Comment by KillerOfPie** [comment]
> * If Permissions properly work without a permissions plugin and with internal-permissions disabled then remove internal permissions.

`If Permissions properly work without a permissions plugin and with internal-permissions disabled then remove internal permissions.` yes.



> Also, I think the default status should **not** be made configurable

Agreed.



> Name	Enabled by default?
> Help	yes
> Create	yes
> Create Infinite	no
> Create Bi	yes
> Admin	no
> Edit	yes
> Info	yes
> Manage Plugin	no
> Prevent Trade	N/A: we would remove this one

Prevent Trade should be replaced with Trade which would be enabled by default, edited your table to reflect this since I will probably build off of that.

**Comment by KillerOfPie** [comment]
Completed in #127
