### ISSUE TITLE
Certain items not registering In Stock

### ISSUE THREAD

**Issue by dtawales** [SparklingComet/TradeShop#141]
### Expected behavior

Magenta and Purple stained glass, when correctly set up into a chest shop, should show in stock when the required quantity is placed inside the chest.

### Observed/Actual behavior

Magenta and Purple stained glass show out of stock despite having the required quantity in the tradeshop chest.

### Steps/models to reproduce

[trade]   then /ts addproduct X amount of purple/magenta stained glass blocks
/ts addcost any cost

Place item in the tradeshop

Observe a continued out of stock notification

### Plugin list

Essentials, Luckperms, Tradeshop, TAB, WorldGuard, CoreProtect

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads

TradeShop-2.5.1-Stable

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

**Comment by KillerOfPie** [comment]
Pretty sure this problem was already reported and fixed in the latest dev build. Please try using that on a test server if possible.

**Comment by KillerOfPie** [comment]
Fixed in #127
