### ISSUE TITLE
Add support for LWCX

### ISSUE THREAD

**Issue by FireController1847** [SparklingComet/TradeShop#142]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

I'd like for members added via LWCX to automatically have permission as "Member" levels. Maybe even players added via LWCX's "admin" level, could be given the "Manager" level equivalent in this plugin.

### Describe alternatives you've considered.

I do not have any alternative ideas.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported TradeShop build.
- [ ] I have asked the Developers and they have confirmed that it is not already in development.

### Other

I really enjoy this plugin so far, thank you!

**Comment by SparklingComet** [comment]
Sincere apologies for the late reply.

Adding LWCX-integration in the main plugin is not feasible in terms of the required maintenance work for this... This would be suited well to a TradeShop add-on (see wiki: https://github.com/Tradeshop/TradeShop/wiki/TradeShop-Addon-Framework).
Creating such an add-on should be fairly easy, you can do so yourself or commission a dev. Feel free to join our discord server for questions and help: https://discord.com/invite/qzdSUnw
