### ISSUE TITLE
Compare Durability Bugged

### ISSUE THREAD

**Issue by Ryne9732** [SparklingComet/TradeShop#143]
### Expected behavior

When flipping the Compare Durability option for an armor piece it should allow me to trade any durability of armor for the product

### Observed/Actual behavior

When I close the menu the compare durability flips back to green and I cant trade how I want.

### Steps/models to reproduce

Set armor piece as cost. change compare duribility, close window and reopen and its changed back.

### Plugin list

Citizens, Dungeons, eco, EcoArmor, EcoEnchants, Essentials, EssentialsChat, ItemEdit, KeepChunks, LibsDisguises, LPC, LuckPerms, LuckPermsGUI, Minepacks, MyPet, MythicMobs, NickNames, OpenAudioMc, OpenInv, PlacegolderAPI, PlayerParticles, ProtocolLib, Quests, Sentinel, SkinsRestorer, ToolAndFoodFX, TradeShop, UltraCosmetics, WorldEdit, WorldGuard

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

tradeshop-2.5.1-STABLE-2022-04-16T17.13.24.jar

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

### Other

Just trying to make an easy repair shop for players armor. If theres away around this too I can consider that.

**Comment by KillerOfPie** [comment]
Been super busy, sorry I missed this.

This may be fixed in the dev version/next release. If not let me know and I will find it when I have time.

**Comment by KillerOfPie** [comment]
Fixed in the latest dev release
