### ISSUE TITLE
Hopper Issue (1.19.2)

### ISSUE THREAD

**Issue by TremxNeo** [SparklingComet/TradeShop#144]
### Expected behavior

Hoppers don't extract/import items when it is disabled

### Observed/Actual behavior

Hoppers still extract/import items when it is disabled

### Steps/models to reproduce

1. Use minecraft 1.19.2
2. Create a tradeshop
3. Put hopper above/below chest
4. Items are still moved

### Plugin list

Chunky, ChunkyBorder, CraftControl-RCON*, dynmap, floodgate, Geyser-Spigot, Graves, GSit, ImageOnMap, LuckPerms, SkinsRestorer, TabTPS, TradeShop, UltimateAutoRestart

### TradeShop version and Minecraft version (CraftBukkit/Spigot/Paper/...)

TradeShop 2.5.1-STABLE
Minecraft 1.19.2 Paper

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] My version of Minecraft and TradeShop are supported by the TradeShop Dev Team (when in doubt, first ask on the [Discord](https://discord.link/TradeShopPlugin)).

### Other

Other features work fine, it is only the hoppers that are problematic

**Comment by SparklingComet** [comment]
For the sake of troubleshooting please try the latest Dev build and see if it works.

// Edit:
Do not keep the Dev build after you test it, please report your findings and then switch back to the stable version.

**Comment by KillerOfPie** [comment]
Pretty sure I changed how hoppers work in the latest dev version, so not only should it work there should be improvements.

**Comment by TremxNeo** [comment]
I tested the latest dev build and it shows the same result

https://user-images.githubusercontent.com/67651877/194686428-7fe9cbec-48a2-4056-ac63-a671a3e13097.mp4

**Comment by KillerOfPie** [comment]
> I tested the latest dev build and it shows the same result
> 
>  2022-10-08.11-36-36.mp4

While looking at the sign, use `/ts edit`, then select settings? I think it is, there should be an export setting there try toggling that.

**Comment by KillerOfPie** [comment]
Going to assume this is Fixed in #127 someone will report again if not.
