### ISSUE TITLE
64 Items are one ?

### ISSUE THREAD

**Issue by oliverxsch** [SparklingComet/TradeShop#2]
Hi,
im testing in Minecraft 1.12 and when i want to sell 64 bones for one iron with a shop.
You can sell it too when you only have 63 bones or just one bone!
Nagerox

**Comment by SparklingComet** [comment]
Copy pasting from #1:
@KillerOfPie , was this fixed in your patch? If yes, the latest JAR from SpigotMC should contain the fix.

**Comment by KillerOfPie** [comment]
Yes it was fixed in the latest patch

**Comment by SparklingComet** [comment]
Alright, thank you. Closing.
