### ISSUE TITLE
New Custom Item trading not working

### ISSUE THREAD

**Issue by beautifulpoison** [SparklingComet/TradeShop#34]
So I figured out how to create the tradeshop on my own, created the custom items when I was holding each of them. Besides the issues in the photo, another issue is that when I create the TradeShop sign, it tells me the tradeshop is empty when it actually is not. 

Photos of the other issue https://imgur.com/a/INv4C

**Comment by SparklingComet** [comment]
Can we see your configuration? Also please check your console log for potential errors.

**Comment by beautifulpoison** [comment]
Config: https://hastebin.com/wagewewebe.sql
Custom Items: https://hastebin.com/etusepimij.scala

No errors or messages in console.

**Comment by KillerOfPie** [comment]
@beautifulpoison try using /getci <item name> for both your items and tell me what happens

**Comment by beautifulpoison** [comment]
Unknown command

**Comment by KillerOfPie** [comment]
/ts getci   sorry forget my 9wn commands sometimes

**Comment by beautifulpoison** [comment]
![screen shot 2017-10-23 at 1 49 07 pm](https://user-images.githubusercontent.com/29660713/31908469-96a8663a-b7fc-11e7-9723-c8c51b73914a.png)

**Comment by KillerOfPie** [comment]
Do '/ts getci votekey' and '/ts getci rank-upkey'

**Comment by KillerOfPie** [comment]
@beautifulpoison I copied your config and custom items and tested it and it all seems to be working, i may have to hop on your server to test if you are still having the problem

Also if the Â is in there to make it a specific item that a player cant make(besides the enchantment) you can also just add blank color codes to the end, i.e
§aThe key to your dreams.§4§0§4 is not the same as §aThe key to your dreams.
and the ending color codes wont show in-game

**Comment by beautifulpoison** [comment]
Okay, the /ts getci works fine and gives me the keys as it's supposed to. No matter what I do, the crate does not work. You can come on my server but your access will be limited as this is on a server that hasn't been launched yet.

**Comment by KillerOfPie** [comment]
That's fine, and you are sure there are no errors coming up in console?

**Comment by beautifulpoison** [comment]
It still says the shop is empty with 154 keys in it... And the same thing in chat everytime..

**Comment by beautifulpoison** [comment]
Nothing logs to console from the plugin when the shop is created or when the player is trying to buy

**Comment by KillerOfPie** [comment]
What's the server ip, I'm going to work now but I'll be able to check it out tonight or tomorrow

**Comment by beautifulpoison** [comment]
We got it working... I don't even know how.

**Comment by KillerOfPie** [comment]
Cool, I don't either. But let us know if you have problems again

**Comment by beautifulpoison** [comment]
For sure!

**Comment by SparklingComet** [comment]
Closing. Feel free to reopen if you need help again.
