### ISSUE TITLE
1 for 2 trading

### ISSUE THREAD

**Issue by arvitus** [SparklingComet/TradeShop#44]
Hi,

Can you implement the 1 for 2 trading? 
Means: You are selling 1 Diamond for 1 Gold AND 1 Iron.

**Comment by KillerOfPie** [comment]
@TrueMAMA due to the way our signs currently work that wouldn't be possible. However we may look into into after the 2.0 update.

**Comment by KillerOfPie** [comment]
This is being added in V2.1.0, sorry it took so long.
Closing.
