### ISSUE TITLE
Not trading the right ammount

### ISSUE THREAD

**Issue by MamaBeau** [SparklingComet/TradeShop#48]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [ ] I have updated to the [latest TradeShop version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

The items are not trading for the right amount, As shown in the photos here: https://imgur.com/a/3cxsk the items are supposed to be trading 175 for 1 and it comes up saying its trading 350 for 1.

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
What version are you using?
Are you crouched when you try to buy? 
Do any errors show up in console?

**Comment by MamaBeau** [comment]
Version: TradeShop 1.7.0-BETA
Not crouched when they try to buy it.
No errors in console other than the "You do not have 350 keys"

**Comment by KillerOfPie** [comment]
Update to the newest version and let me know if you still have the problem

**Comment by MamaBeau** [comment]
Updating the plugin worked. Thank you.
