### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by Etanarvazac-zz** [SparklingComet/TradeShop#49]
Doesn't work at all unless you're opped. I even tried giving full access to Guest perm group (tradeshop.*) and was still told they didn't have permission to make shops

![capture](https://user-images.githubusercontent.com/16289987/36607598-0870f3ce-1895-11e8-803c-4bda571c2ff8.PNG)

**Comment by SparklingComet** [comment]
Thank you for your report.
Do you nave any other plugins which could operate on signs or chests? There might be a conflict.

**Comment by KillerOfPie** [comment]
@Etanarvazac What other plugins are on your server, what version of TradeShop are you using, and what version of MC?

**Comment by SparklingComet** [comment]
Closing. If you wish further assistance, please reopen the issue by replying to the thread.
