### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by Lawson-a** [SparklingComet/TradeShop#50]
Hello, I am trying to use this plugin for a custom currency on my server. But when i setup a trade sign with a custom token, i used a slime ball with specific meta values on it, it will also take regular slime balls.

Is there a fix?

**Comment by SparklingComet** [comment]
Are you configuring the `customitems.yml` file correctly? You basically need to give your special slimeball an alternative name and use that one on the sign.
(Like “coin”, or just”slimes” - note the “s” st the end)

**Comment by KillerOfPie** [comment]
@slimeguy24 [Here's a link to the wiki page on custom items](https://github.com/SparklingComet/TradeShop/wiki/Custom-Items), make sure you're using them for it to work properly. If it still does not seem to be working and you are on the newest version then give us an ip if possible and I can get on and try to figure out whats not working.


https://github.com/SparklingComet/TradeShop/wiki/Custom-Items

**Comment by Lawson-a** [comment]
@sparklingcoment I gave myself a slime ball with the name Slime Token and a special lore and I type /ts additem SlimeToken 
And it adds the item just fine but when a user goes to a sign where u use the slime token to pay for an item they can just have normal slime balls in their inventory, it dosent take the normal slime balls but it still puts a slimetoken in the chest and gives them the item for free

**Comment by KillerOfPie** [comment]
@slimeguy24 can you paste your customitem.yml file here?

**Comment by Lawson-a** [comment]
![customitems](https://user-images.githubusercontent.com/37918645/38143121-10ac70de-340d-11e8-8001-0c63e536b98a.PNG)

**Comment by KillerOfPie** [comment]
@slimeguy24 and you're on the newest version of the plugin and at least 1.12?

**Comment by Lawson-a** [comment]
yes I am

**Comment by KillerOfPie** [comment]
@slimeguy24 do you have an ip for the server?

**Comment by KillerOfPie** [comment]
wrong button...woops :P

**Comment by SparklingComet** [comment]
Closing. If this is not fixed, reopen the issue.
