### ISSUE TITLE
Chests placed diagnolly to TradeShop chests will Flag the chest as part of the TradeShop

### ISSUE THREAD

**Issue by creezd** [SparklingComet/TradeShop#51]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/
  
- [YES] I have checked for similar issues.
- [YES] I have updated to the [latest TradeShop version][download].
- [YES] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [YES] Bug Report
- [ ] Feature Request

### Description

Placing a chest diagnol to an existing TradeShop chest will flag it as part of the TradeShop.

**Comment by KillerOfPie** [comment]
Would you be able to provide us with a picture of how the chests are placed

**Comment by SparklingComet** [comment]
Closing as this will not be an issue in 2.0.

**Comment by KillerOfPie** [comment]
He said he was closing it but he didn't so now i will almost a year later :P
