### ISSUE TITLE
Item isn't trading

### ISSUE THREAD

**Issue by icourt** [SparklingComet/TradeShop#52]
Hi,

I setup a tradeshop that is the following:
1 emerald -> 1 diamond

If I only have 1 diamond in stock, a player can right click and get the diamond, without trading the emerald. This happens on [Trade] and [BiTrade] shops (not even sure what BiTrade is)

Can you please fix this!
Thanks!

**Comment by KillerOfPie** [comment]
What version of minecraft? What version of the plugin? Does anything show up on console? And is it a public server?

**Comment by icourt** [comment]
MC Version: 1.12.2
Plugin Version: 1.8.1
Does anything show up on console?: Yes, hastebin below.
Public server?: No, but I can invite you if you want.
- https://hastebin.com/itumopeteh.cs

**Comment by icourt** [comment]
Also, when I setup a shop to trade 1 emerald for 1 diamond, players can successfully trade it if I have enough stock, but chat says this every once in a while - https://imgur.com/a/fM6LGH3

**Comment by KillerOfPie** [comment]
Here's a wiki link for the sign type - https://github.com/SparklingComet/TradeShop/wiki/Custom-Items

Also I'll be off in a couple hours and I'll work on fixing this asap. Should be done tonight if all goes right.

**Comment by KillerOfPie** [comment]
@icourt1 sorry it took so long just finished fixing it, gotta test real quick and have @SparklingComet upload it, look for the 1.8.2 version hopefully tonight

**Comment by KillerOfPie** [comment]
And this ladies and gents is why we don't copy and past code without double checking it

**Comment by KillerOfPie** [comment]
@icourt1 version 1.8.2 is up on spigot, I'm going to close this issue as it should be resolved. Open another one if you find any other problems.
