### ISSUE TITLE
Hoppers are able to take things from the trade chest.

### ISSUE THREAD

**Issue by smashedbotatos** [SparklingComet/TradeShop#58]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest TradeShop version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description
Hoppers are able to take things from the trade chest.

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
For some reason I never checked that, I should have time to fix that tomorrow.

**Comment by KillerOfPie** [comment]
Fixed in #60 same as closing comment on #57
