### ISSUE TITLE
Error: Sign not recognizing adjasent chest

### ISSUE THREAD

**Issue by mrkylen** [SparklingComet/TradeShop#62]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [X] I have checked for similar issues.
- [X] I have updated to the [latest TradeShop version][download].
- [X] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [X] Bug Report
- [ ] Feature Request

### Description

TradeShop ver 2.1, when placing sign to make a shop get the msg:
"You need to put a chest under the sign!"
No matter where on the chest I place the sign. Can make an [iTrade] sign, but when I try to open the shop i get msg:
"Your shop is missing a chest"

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
Fixed
