### ISSUE TITLE
2.0.2 Error: "You need to place a chest under the sign"

### ISSUE THREAD

**Issue by xShqdow** [SparklingComet/TradeShop#63]
When creating a trade shop and placing the sign with the right format, it says "You need to place a chest under the sign!"
I have read the other bug reports. but they are all older versions. We have TradeShop 2.0.2 installed on our Papermc 1.14.4 server. 
Console: https://pastebin.com/ne2jhvCH

**Comment by KillerOfPie** [comment]
Error has already been fixed for 2.1.
