### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Kalikanto** [SparklingComet/TradeShop#64]
## General Troubleshooting

Hey there! Before you report a feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar feature requests.
- [x] I have checked for [planned feature requests][https://github.com/SparklingComet/TradeShop/projects].
- [x] I have checked the branches or the maintainers' PRs for upcoming added features.

### Description

**My request is that Shop Users/Members/mnagers/Owners can trade in their own shops too by clicking on the sign. I don't know why it couldn't be possible.**

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
It is possible however I don't think that's something we will be adding for a couple reasons.

1. Any user of a shop can open the shop and manually trade items

2. It would cause problems when owners try to break the shop, making it impossible to break without a command.
