### ISSUE TITLE
Yo how do I do perms

### ISSUE THREAD

**Issue by Buttered-Alex** [SparklingComet/TradeShop#65]
Okay so listen up i have a server and I want to give the players the ability to make their own shops however I don't know how I have a perms manager rom another plugin (Essentials) and I tried putting in the perms node but it didn't work and there was no place in this plugin config where I could but the nods nor was there a spot for me to make people without op to  be able to make a shop plz help

**Comment by KillerOfPie** [comment]
The easiest way to do that would be to look up an introductory video on YouTube for whatever plugin you are using for the permissions. Unfortunately most permissions plugins do things differently so it is a little difficult for us to be able to walk you through doing it. Also, our discord is a much better place to ask for support. This would be more for bug reports and feature requests.
