### ISSUE TITLE
[FEATURE] Cosmetic item display above chests

### ISSUE THREAD

**Issue by ghost** [SparklingComet/TradeShop#67]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here][https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels].

## General Troubleshooting

Hey there! Before you report a feature,
  please make sure to follow these steps first!
  
- [x] I have checked for similar feature requests.
- [x] I have checked for [planned feature requests][https://github.com/SparklingComet/TradeShop/projects].
- [x] I have checked the branches or the maintainers' PRs for upcoming added features.

### Description

This feature will allow for the displaying the items being traded above the respective chest. The items are cosmetic/aesthetic to the shop and can't be picked up, interacted with or destroyed and will no longer display if the shop doesn't exist anymore.For single chests, the items could cycle between the two being traded or they could be displayed on either ends of the chest of it's a double chest. This could also be configurable in the plugins configuration to be enabled or disabled (and possibly toggleable in game on a per shop type basis by the creator of a shop?).

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
I'll add this to the project list later, however, atm I can't think of a good way to do this now that we support multiple items.

If I do it I will probably make it a plugin once @SparklingComet has that done so that only the servers that want it would need to install it.

**Comment by SparklingComet** [comment]
This is a planned addon. I have added this to the todo list for after release 2.3.0.
