### ISSUE TITLE
[BUG] Existing Tradeshop signs attempt to link to all newly placed containers neraby

### ISSUE THREAD

**Issue by paularcoleo** [SparklingComet/TradeShop#73]
By placing a new container near an existing TradeShop sign, the sign links to that new container. This can result in several issues:

1. You cannot create a new TradeShop next to an existing one.
2. Placing and then removing the new container will break the existing TradeShop. The existing shop will become closed, and if you attempt to open it with `/ts open`, you will receive the error `Your shop is missing a chest`. This occurs even if the existing shop is a double chest. Removing and replacing the TradeShop sign on the existing shop does fix this. However, if the existing shop is a double chest, this would remove protections on the second half of the double chest, as shop protections is currently build order dependent as described in #70:

>  Currently, double chest protection is dependent on the order in which you place the chests and tradeshop sign. If you place chest 1, then make a sign, then chest 2, then as described above, they will be considered the same inventory block. However, if you place both chests to create a double chest, and then add the tradeshop sign, you can add two tradeshop signs to the double chest. This has an upside and a downside. The downside is that if a user sets up their chest this way, but doesnt put down a second sign, the side of the double chest without a sign is vulnerable to being broken.

  The user would have to break the 2nd half of the chest, replace the sign, and then replace the 2nd half of the chest in order to re-enable protections, and this would cause any contents in the 2nd half of the chest to spew out.

3. If you do attempt to create a new TradeShop sign on a linked container, it will result in an invalid sign (Trade will be in red text). This then opens up the bug described in #70 where the existing shop could retain its named ID if destroyed before the shop sign. However, if 2.3 moves away from naming containers, as proposed in #70, then this point will be solved.

**Comment by paularcoleo** [comment]
Just had this come up again - another player put down a shulker box in front of one of my shop signs, and then couldn't put their purchase into the box because it had linked to the sign, and thus under protection. Luckily I was there at the time and was able to break and move their shulker for them. It also then breaks my shop as explained in point 2 above.

**Comment by SparklingComet** [comment]
Hello,
thank you for your report. Indeed, it appears that the current sign-chest linking system is faulty, hence why we will be changing the way links and chests are connected in the next major release. The new system will most likely not have these shortcomings.
I think that instead of attempting to fix all the problems the current system has, it would be more efficient to roll out the new solution.
In the meantime, thank you for your patience and all of your reports.

**Comment by KillerOfPie** [comment]
The initial linking system hasn't been changed but this should be fixed in 2.2.2
