### ISSUE TITLE
[BUG] Specific trade chests will not allow to open a new shop because of a shop previously existing at the block coordinate

### ISSUE THREAD

**Issue by Eric17314** [SparklingComet/TradeShop#74]
When creating a shop, upon destroying the sign and chest, any attempt to create a new shop at the same block coordinate displays a message that says “You may only have 1 shop per inventory block.” Despite there no longer being a shop at that specific coordinate. This issue is only affecting 3 specific chests, when attempting to do the same on any other chest, the issue does not occur.

**Comment by SparklingComet** [comment]
Is there a reason why this was closed?
Ie. do you intend to cancel this issue?

**Comment by Eric17314** [comment]
I closed this issue because upon further inspection I thought it was
similar to other issues already listed.
