### ISSUE TITLE
[FEATURE] order-independent shulkers

### ISSUE THREAD

**Issue by paularcoleo** [SparklingComet/TradeShop#75]
Currently, when shulkers containing multiple items are added as a tradeshop product, the order of the items in the shulkers must be exactly the same as the shulker used to create the shop. So if a shulker had 2 different items swapped inside, the shulker wouldn't count be counted as part of the shop's stock. Not a deal breaker but a bit annoying if you're trying to sell a kit of items.

Perhaps when the shop is determining if there is sufficient stock, it could compare a sorted dictionary of item/qtys if a filled shulker was specified as the product, rather than the exact metadata?

**Comment by KillerOfPie** [comment]
For shulkers i can compare the inventories they have differently to allow for this to work. It may create some extra overhead when trading with shulkers though so may be something that I give the option to disable in the settings.

This will probably be worked on in the next version.

@paularcoleo would this be sufficient?

**Comment by paularcoleo** [comment]
Yea, that all makes sense.

**Comment by KillerOfPie** [comment]
I think I have added this, hopefully it works correctly. If it doesn't it may be removed and properly added later.
