### ISSUE TITLE
[FEATURE] Add option to allow trading with own shops (primarily for testing/debug)

### ISSUE THREAD

**Issue by RobinWhitfield** [SparklingComet/TradeShop#77]
An option to allow owners to purchase from their own shops, primarily for debugging/testing purposes, by both users and admins.

Could even be a change of the "You cant buy from a shop in which you're a user" to include a confirmation option. Something like:
"You are a user of this shop, are you sure you want to trade? [confirm]"

**Comment by SparklingComet** [comment]
This has been suggested several times already and I can absolutely see why it would be very useful. We are considering adding this in v2.3.0 as modifications to plugin mehanics need to be rolled out first.

**Comment by KillerOfPie** [comment]
I've added this to the latest dev build, after working on organizing the settings and everything it seemed to be a very simple change. If any hard to trace bugs pop up it may be removed and re added in v2.3.0
