### ISSUE TITLE
[BUG] [2.2.2 BETA] Shop chests can be opened by non-shop owners

### ISSUE THREAD

**Issue by RobinWhitfield** [SparklingComet/TradeShop#80]
tradeshop-2.2.2-BETA-2020-05-19T18.50.13.jar

Currently running Paper 300

![image](https://user-images.githubusercontent.com/63362209/82539104-c2698c80-9b44-11ea-90d6-1eeaca465239.png)

**Comment by KillerOfPie** [comment]
I may have fixed this. It was still using old code so i rewrote the entire section a little better and hopefully that's enough to get it to work properly. Again will send jar after I've looked at the last issue.
