### ISSUE TITLE
[BUG] [2.2.2 BETA] iTrade shops cannot be destroyed

### ISSUE THREAD

**Issue by RobinWhitfield** [SparklingComet/TradeShop#81]
tradeshop-2.2.2-BETA-2020-05-19T18.50.13.jar

itrade signs simply re-appear when destroyed. They can only be destroyed by removing the block they're attached to

On break:
https://pastebin.com/C8hB7kd8

**Comment by KillerOfPie** [comment]
I think I got this too. Seems to be because I was trying to get the players Inventory Storage Contents (only exists when the player opens an inventory).

**Comment by SparklingComet** [comment]
has this fix been tested?

**Comment by KillerOfPie** [comment]
This is fixed in the latest dev release
