### ISSUE TITLE
[BUG] [2.2.2 BETA] Existing signs change container association and link to newly created adjacent chests.

### ISSUE THREAD

**Issue by RobinWhitfield** [SparklingComet/TradeShop#82]
tradeshop-2.2.2-BETA-2020-05-19T18.50.13.jar

Paper 300

Creating a single chest on either side of an existing shop causes the shop sign to link itself to the newly created chest.

![image](https://user-images.githubusercontent.com/63362209/82539674-ba5e1c80-9b45-11ea-8613-91c712bc8b25.png)

**Comment by KillerOfPie** [comment]
I think i got this fixed, will send a new jar in a bit after I look at the other reports.

**Comment by paularcoleo** [comment]
duplicate of #73?

**Comment by KillerOfPie** [comment]
Yes but I think a different cause

**Comment by SparklingComet** [comment]
This should be fixed in the current release, closing.
