### ISSUE TITLE
[FEATURE] More Message Customization

### ISSUE THREAD

**Issue by tkn0** [SparklingComet/TradeShop#83]
Please add the config options to alter the help menu and the prefix seen before each message.

**Comment by SparklingComet** [comment]
Prefix will perhaps be configurable in a future release. About the help message, there are currently no plans yet to make it customisable. There are other ways for a server administrator to offer custom help.

**Comment by tkn0** [comment]
Is it okay if I add these features to the plugin myself for a public server or is that against your terms?

**Comment by KillerOfPie** [comment]
Prefix is already customizable in the next release, The help menu customization may be added in a future release. However it wont be entirely customizable seeing as it is built using many built in values that are also used for validating commands and such.

As far as adding the changes yourself, you can fork the project on Github and make any changes you would like. The plugin is under the [Apache License](http://www.apache.org/licenses/LICENSE-2.0) so you can see that if you intend to make changes. You can also make your changes and submit a pull request for the changes to be added to the plugin.

**Comment by SparklingComet** [comment]
Another option is custom `/help <plugin>` instead of changing `/<plugin> help`. There is plenty of resources that make way for this.
