### ISSUE TITLE
[BUG] Null Pointer Exception in Console when using TS WHAT

### ISSUE THREAD

**Issue by tkn0** [SparklingComet/TradeShop#84]
https://hatebin.com/vgdtehtcuq
A null pointer pops up in console sometimes when using /ts what.
The issue seems to arrive when no shop is in range or a player uses /ts what in the open.

**Comment by SparklingComet** [comment]
Thank you for taking your time to report this. I believe this is already fixed for the next release, which is being tested. It should be out soon

**Comment by SparklingComet** [comment]
On closer inspection, it appears this was not fixed. It is now, though, and the patch will be out soon with the next release. Thanks again for your report.

**Comment by tkn0** [comment]
Thanks, guys, was gonna go in and see for myself if I could fix it. But you guys are on it!
