### ISSUE TITLE
[BUG] Could not pass event InventoryMoveItemEvent - NPE

### ISSUE THREAD

**Issue by tkn0** [SparklingComet/TradeShop#85]
Console Error Message found here.
https://hatebin.com/zzqzlifqso
I cannot seem to find the cause of this.

**Comment by SparklingComet** [comment]
Can you explain the context/circumstances? There is a similar problem with composters/hoppers which was fixed a while ago, although the patch is yet to be released with v2.2.2 (#68 )

**Comment by tkn0** [comment]
I really can't find the context it will just appear in console randomly, I assume it has to do with hoppers because the error reports hopper tiles.

**Comment by KillerOfPie** [comment]
This has already been reported #68 and fixed for version 2.2.2
