### ISSUE TITLE
[BUG] Product item not properly given when customer has full inventory

### ISSUE THREAD

**Issue by paularcoleo** [SparklingComet/TradeShop#86]
(2.2.0-BETA)

A mod on our server just sent me video footage of the following scenario.

Customer's inventory is full. One of the slots is 2 diamonds. The cost of the trade he's attempting to perform is 1 diamond. When clicking the sign, nothing happens as expected - no space. The customer then drops 1 diamond, so they now only have 1 diamond in their inventory. The trade "goes through" - the diamond is taken from their inventory, arrives in the chest, an item is taken from the chest, but **no item is delivered to the customer's inventory**.

There appears to be a check that ensures that the player would have inventory space once the diamond is taken, but perhaps there is an issue with the order of the transaction.

**Comment by KillerOfPie** [comment]
This is already fixed for the next version, thank you for the report!

**Comment by paularcoleo** [comment]
Ah, good to know. Sorry if it was a duplicate - I looked through the closed issues but didn't seem to find anything that matched.
