### ISSUE TITLE
[BUG] Sign creation fails if player is lacking sign color perms

### ISSUE THREAD

**Issue by Androiddude73** [SparklingComet/TradeShop#87]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here][https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels].

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest TradeShop version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

Trade Shop signs use colored text when a player makes them (for example, they type [Trade] in the first line, and the plugin adds a color code to the beginning of that), because of this, players that don't have the ability to use color codes on signs are not able to make trade shops. (On my server, this ability is a rank perk, so not everyone has it) The sign will say &2[Trade] and so on. This means the trade shop doesnt actually work, because there are extra characters.

In order to reproduce this you would need to disable the permission to use color codes on signs, I'm not sure how this is done (I don't work with our ranks), but once you do you'll see that when you try to set up the shop, the color codes are added automatically but don't actually make the color

What the player without permission to use color codes types:
![image](https://user-images.githubusercontent.com/58871551/91750159-784a6b00-eb77-11ea-854d-67edad8ac821.png)

What comes out when they press done:
![image](https://user-images.githubusercontent.com/58871551/91750226-9912c080-eb77-11ea-80e0-30a6dea45c6b.png)

### Console Error

N/A

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by SparklingComet** [comment]
Type just `[Trade]` and see what happens (no colors, other lines blank).
Also please list any plugin on your server which involves sign color.

**Comment by Androiddude73** [comment]
![2020-08-31_11 31 37](https://user-images.githubusercontent.com/58871551/91754181-d9753d00-eb7d-11ea-9e0d-730d519fec5f.png)

This is what happens when a player without our permission to color signs types only [Trade] on the first line

We use CMI to add and remove permission for sign coloring i believe

**Comment by SparklingComet** [comment]
> We use CMI to add and remove permission for sign coloring i believe

Can you try this without CMI?

**Comment by thecenters** [comment]
We know this is CMI causing it because it's permission based. There's nothing in any of the configs to remove the color codes from the signs. How can we remove the coloring?

**Comment by KillerOfPie** [comment]
I have already built this in to the dev version.

**Comment by KillerOfPie** [comment]
@thecenters I have implemented the work around into the latest Dev build for 2.2.2, which is available for download on the release page. All this does right now is allow you to change the color codes that are used on the signs(or remove them entirely)

I will probably work on actually fixing this(to not require the sign color perm) in our next release
