### ISSUE TITLE
[BUG] Removing direction from allowed-directions displays SHOP_BAD_COLOUR on signs

### ISSUE THREAD

**Issue by James76931** [SparklingComet/TradeShop#91]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here][https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels].

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [x] I have checked for similar issues.
- [x] I have updated to the [latest TradeShop version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

When a direction is removed from allowed-directions in the config file, placing a [Trade] sign on the disabled direction causes the message "SHOP_BAD_COLOUR" to be displayed on the first line of the sign.

In this image example, I have 'up' removed from allowed-directions.
**
![image](https://user-images.githubusercontent.com/15969024/97079768-6ffa3380-15ee-11eb-840a-d1f664361c9b.png)
**

### Console Error

<details> 
  <summary> </summary>

   No console error present.

</details>

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
What version of the plugin are you using?

**Comment by James76931** [comment]
The latest Spigot release, 2.2.4-STABLE

**Comment by KillerOfPie** [comment]
I just confirmed I had this fixed for 2.3.0 but forgot to pull the fix back when i was doing 2.2.3 and 2.2.4. This is minor so it will wait until 2.3.0 is released.

**Comment by KillerOfPie** [comment]
This was fixed in 2.2.5
