### ISSUE TITLE
[BUG] iTrade signs without cost item gives Index out of bounds 0 error.

### ISSUE THREAD

**Issue by RobinWhitfield** [SparklingComet/TradeShop#93]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

Explanation of the label system for Issues may be found [here][https://github.com/SparklingComet/TradeShop/wiki/Issue-&-Pull-Request-labels].

## General Troubleshooting

Hey there! Before you report a bug,
  please make sure to follow these steps first!
  
- [x ] I have checked for similar issues.
- [x ] I have updated to the [latest TradeShop version][download].
- [x ] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

v2.2.5 STABLE

Placing an iTrade sign without a cost item results in an Index out of bounds error when you try and use it.
I can't see any bug fixes in latest dev that would fix this although it has not been tested.

### Console Error

<details> 

https://pastebin.com/kchWVyD9

</details>

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by KillerOfPie** [comment]
This should be fixed in latest Dev code, will post a new jar later today
