### ISSUE TITLE
Would it be possible to you able to sell fireworks with different durations?

### ISSUE THREAD

**Issue by igyboo** [SparklingComet/TradeShop#94]
[download]: https://www.spigotmc.org/resources/tradeshop.32762/

## General Troubleshooting

Hey there! Before you report a bug or suggest a new feature,
  please make sure to follow these steps first!
  
- [ ] I have checked for similar issues.
- [ ] I have updated to the [latest TradeShop version][download].
- [ ] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

Replace this sentence with a description and include as many details as you think are needed to understand your issue.

## Credits & Disclaimer

This file contains parts that were taken from [the JDA project](https://github.com/DV8FromTheWorld/JDA).
We do **not** wish to take credit for those parts.
Everything is licensed under the [Apache License v2.0](https://github.com/SparklingComet/TradeShop/blob/master/LICENSE).

**Comment by ess3sq** [comment]
The general procedure to sell any kind of “special items” (as in items with non-standard metadata) would be through the `ts additem` command. Hold the item in your hand and execute it while staring into the sign’s hitbox.

**Comment by SparklingComet** [comment]
To add an item, hold it in your hand while staring into the sign’s hitbox and execute `/ts addproduct`.

Let us know if that fails

**Comment by igyboo** [comment]
You, can add and item but fireworks can't be addded as you can only add fireworks without any tags.

**Comment by SparklingComet** [comment]
So, to confirm, you tried this and you got a firework with regular metadata? (As in regulae attributes instead of the ones of the item you supplied)

**Comment by igyboo** [comment]
Yes, exactly. And the the regular fireworks, cant be created in survival mode i cant sell any.

**Comment by SparklingComet** [comment]
I see, please share your server and plugin version. If it is not the last official release or the latest dev build, please update and check whether the issue persists.

**Comment by igyboo** [comment]
I have this version: "tradeshop-2.2.5-STABLE.jar"

**Comment by SparklingComet** [comment]
I apologise for the extreme delay. This functionality was added and wil be available in the next release (v2.3.0; #92 )
