### ISSUE TITLE
[BUG] Any player can open shop chests

### ISSUE THREAD

**Issue by lagnat** [SparklingComet/TradeShop#95]
### Description

Any player can open any shop chest.  You might have had someone ask you about this problem on your discord.  With debug enabled, I see this message `Storage Block PerData: null` which I think means the plugin doesn't think it's a shop chest despite having the proper sign and json file.  Breaking the sign, and re-creating the shop fixes the problem.  The server owner told me that the shops were created with an older version of the plugin.

**Comment by SparklingComet** [comment]
Please state the server and plugin version, as well as the older plugin version from which the server owner presumably upgraded.

**Comment by lagnat** [comment]
Server was probably Paper 322.
Plugin version 2.2.5-STABLE

As for previous version, I do not know.  I only help the owners with their server when they have problems.  I can probably get you one of the problematic json files, if that would help.

**Comment by KillerOfPie** [comment]
Can not duplicate, closing.
