### ISSUE TITLE
[BUG] TraderShop Updater outputs WARN instead of INFO

### ISSUE THREAD

**Issue by HandyHat** [SparklingComet/TradeShop#96]
## General Troubleshooting

- [X] I have checked for similar issues.
- [X] I have updated to the latest TradeShop version (v2.2.5).
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

### Description

Upon startup, the TradeShop Updater checks for updates but outputs a WARN even if TradeShop is up-to-date

### Console Error

`[Thread-19/WARN]: [TradeShop] [Updater] You are running the latest version of the plugin!`

**Comment by SparklingComet** [comment]
Thanks for the report, this should be fixed with the next release.
