### ISSUE TITLE
[BUG] "There are too many shops in this chunk, you can not add another one"

### ISSUE THREAD

**Issue by Jurz21** [SparklingComet/TradeShop#99]
### Description

Replace this sentence with a description and include as many details as you think are needed to understand your issue, as well as any steps required to replicate the issue.

### Console Error

<"There are too many shops in this chunk, you can not add another one"> 

  <After placing shops to the chunk limit, and then breaking them to reorganise, the plugin is not allowing any further shops to be place, even after breaking the initial shops>

**Comment by KillerOfPie** [comment]
Please specify what server and plugin versions you are using

**Comment by Jurz21** [comment]
We're using Tuinity Build #224 and TradeShop 2.2.5

**Comment by ess3sq** [comment]
> We're using Tuinity Build #224 and TradeShop 2.2.5

Please try the latest dev build. Although I doubt it fixed this issue, it contains many fixes.

**Comment by KillerOfPie** [comment]
This is fixed in the dev version, although I did find the max is the max in the config - 1 so I will fix that

**Comment by KillerOfPie** [comment]
Fixed in #92 12a4253
